### ISSUE TITLE
Port argument read as string and not integer

### ISSUE THREAD

**Issue by jimpete** [ocadotechnology/nexus-exporter#19]
When using the --port argument, the number is read in as a string which in turn causes the startup to fail. The --port argument content needs to be treated as a number.

±  |master U:1 ?:1 ✗| → docker run -p 9158:9158 nexus_exporter --port 9158
INFO:nexus-exporter:starting nexus exporter on port 9158
ERROR:nexus-exporter:unable to fetch data from metric endpoint: <urlopen error [Errno 99] Address not available>
Traceback (most recent call last):
  File "/nexus_exporter.py", line 267, in <module>
    start_http_server(args.port)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 193, in start_http_server
    httpd = _ThreadingSimpleServer((addr, port), CustomMetricsHandler)
  File "/usr/local/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
TypeError: an integer is required (got type str)

**Comment by stuart-warren** [comment]
wow thanks, have created an MR
