### ISSUE TITLE
KeyError: 'system-runtime'

### ISSUE THREAD

**Issue by kumar-shantanu** [ocadotechnology/nexus-exporter#5]
I tried running this exporter with my nexus installation and it throws below error, (I am running version 3.6.0. of nexus)

Exception happened during processing of request from ('127.0.0.1', 52942)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 76, in do_GET
    self.wfile.write(generate_latest(core.REGISTRY))
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/exposition.py", line 55, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/core.py", line 54, in collect
    for metric in collector.collect():
  File "nexus_exporter.py", line 76, in collect
    i = self._info['system-runtime']
KeyError: 'system-runtime'

**Comment by kumar-shantanu** [comment]
This is working fine with nexus 3.13.0

**Comment by rubencabrera** [comment]
Hi @kumar-shantanu. We state in the README that this works for Nexus > 3.6 because we were aware of some values introduced after that one. Thanks for the update on your issue.
